const priceData=[

  {   id:1,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:2,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:3,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:4,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:5,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:6,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:7,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:8,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
  {   id:9,
      name: 'Carf T1',
      monthly: '24.99',
      annually: '249.99',
      currency: '$',
      benefits: ['1 TB Storage', '5 Users Allowed', 'Send up to 10GB','Send up to 10GB'],
  },
]
export default priceData;
